# -*- coding: utf-8 -*-
"""이코테_스택,큐,DFS,BFS_음료수얼려먹기,미로탈출.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NxrRbVp_6OmGqGYSzKI5UaWkhSjHJo1B

# 1. 자료구조 기초
- 탐색: 많은 양의 데이터 중 원하는 데이터를 찾는 과정
- 자료구조: 데이터를 표현/관리/처리하기 위한 구조
    - 스택/큐: 자료구조의 기초 개념, 다음의 두 함수로 구성됨
        * 삽입(Push): 데이터를 삽입함
        * 삭제(Pop): 데이터를 삭제함

## 1) 스택
선입후출(FILO), 먼저 들어온 데이터가 나중에 나감

프링글스 과자 통에 넣는다고 생각
"""

stack = []

# 프링글스 과자 통에 넣는다고 생각,

# 삽입(5) - 삽입(2) - 삽입(3) - 삽입(7) - 삭제() - 삽입(1) - 삽입(4) - 삭제()
stack.append(5)
stack.append(2)
stack.append(3)
stack.append(7)
stack.pop() # 삭제
stack.append(1)
stack.append(4)
stack.pop() # 삭제

print(stack) # 아래부터 출력
print(stack[::-1]) # 위부터 출력

"""## 2) 큐
선입선출(FIFO), 먼저 들어온 데이터가 먼저 나감

입구 출구 모두 뚫려있는 터널이라고 생각

먼저 들어온 데이터가 오른쪽, 나중에 들어온 데이터가 왼쪽에 위치. 오른쪽부터 삭제됨
"""

from collections import deque  # 큐(Queue) 구현을 deque 라이브러리를 이용하는게 list 보다 우수함
queue = deque()

# 삽입(5) - 삽입(2) - 삽입(3) - 삽입(7) - 삭제() - 삽입(1) - 삽입(4) - 삭제()
queue.append(5) # 오른쪽으로 들어옴 (실제방향)
queue.append(2)
queue.append(3)
queue.append(7) # 7325
queue.popleft()  # 732 # 왼쪽에 있는 데이터를 꺼냄. (실제순서)
queue.append(1) 
queue.append(4) # 41732
queue.popleft() # 4173

print(queue) # 먼저 들어온 순서대로 출력
queue.reverse() # 다음 출력을 위해 역순으로 바꾸기
print(queue) # 나중에 들어온 원소부터 출력 (실제 순서)

# import collections
# print(collections.__all__)

"""## 재귀함수
- 자기 자신을 다시 호출하는 함수
- 모든 재귀함수는 반복문을 이용하여 동일한 기능을 구현할 수 있으나, 경우에 따라 불리할 수도 유리할 수도 있다.
- 스택을 사용해야 할 때 구현상 스택 대신 재귀함수를 이용하는 경우가 많음. 
"""

# # 무한
# def recursive_function():
#     print('재귀 함수를 호출합니다.')
#     recursive_function()

# recursive_function()

# 종료 조건: 실제 코딩테스트에서 필수적 
def recursive_function(i):
    if i == 100: # 100번째 호출을 했을 때 종료되도록 종료 조건 명시
        return
    print(i, '번째 재귀함수에서', i + 1, '번째 재귀함수를 호출합니다.') # 99 번째 재귀함수에서 100 번째 재귀함수를 호출합니다.
    recursive_function(i + 1) # 100 - 조건 충족. 
    print(i, '번째 재귀함수를 종료합니다.') # 99 번째 재귀함수를 종료합니다.

recursive_function(1) # 스택처럼 나중에 호출된 것부터 종료됨

"""### 팩토리얼 구현 예제"""

# 반복적으로 구현한 n!
def factorial_iterative(n):        
    result = 1
    # 1부터 n까지의 수를 차례대로 곱하기
    for i in range(1, n + 1):
        result *= i
    return result

print('반복적으로 구현:', factorial_iterative(5))

# 재귀적으로 구현한 n!
def factorial_recursive(n):        
    if n < 1: # n이 1 이하인 경우 
        return 1 # n! = 1
    return n * factorial_recursive(n - 1) # n! = n * (n - 1)! 점화식
print('재귀적으로 구현:', factorial_recursive(5))

"""### 최대공약수 GCD 계산 (유클리드 호제법) 구현 예제
* 유클리드 호제법: A & B의 최대공약수는, B & A%B의 최대공약수와 같다. 
"""

def gcd(a,b):
  if a%b ==0:
    return b
  else:
    return gcd(b,a%b)

print(gcd(192,162))

"""# 2. 탐색 알고리즘 DFS/BFS

- 그래프 기본 구조: 노드, 간선
    - 그래프 표현 방식
            * 인접 행렬: 2차원 배열로 그래프 연결관계 표현
            * 인접 리스트: 리스트로  그래프 연결관계 표현

## - DFS(깊이 우선 탐색): 멀리 있는 노드 우선 탐색
- 스택이나 재귀함수 이용
- 구현할 때 재귀함수 이용하는 게 좋음

### 동작과정
1. 탐색 시작 노드를 스택에 삽입하고 방문 처리
2. 스택의 최상단 노드에, 방문하지 않은 노드가 하나라도 있으면 스택에 넣고 방문 처리 수행. 방문하지 않은 인접 노드가 없으면 스택에서 최상단 노드 꺼냄
3. 2번을 수행할 수 없을때까지 수행.
"""

# 인접행렬

INF = 999999999 # 무한의 비용 선언

# 2차원 리스트를 이용해 인접 행렬 표현
graph = [
    [0, 7, 5],
    [7, 0, INF],
    [5, INF, 0]
]

print(graph)

# 인접 리스트

graph = [[] for _ in range(3)] # 행(Row)이 3개인 2차원 리스트로 인접 리스트 표현

# 노드 0에 연결된 노드 정보 저장 (노드, 거리)
graph[0].append((1, 7))
graph[0].append((2, 5))

# 노드 1에 연결된 노드 정보 저장 (노드, 거리)
graph[1].append((0, 7))

# 노드 2에 연결된 노드 정보 저장 (노드, 거리)
graph[2].append((0, 5))

print(graph)

# 각 노드가 연결된 정보를 리스트 자료형으로 표현(2차원 리스트)
graph = [
  [],
  [2, 3, 8], # 1번노드의 인접노드는 2,3,8
  [1, 7],    # 
  [1, 4, 5],
  [3, 5],
  [3, 4],
  [7],
  [2, 6, 8],
  [1, 7]
]

# 각 노드가 방문된 정보를 리스트 자료형으로 표현(1차원 리스트)
visited = [False] * 9 # 모든 노드 미방문
# DFS 함수 정의
def dfs(graph, v, visited):
    # 현재 노드를 방문 처리
    visited[v] = True
    print(v, end=' ')
    # 현재 노드와 연결된 다른 노드를 재귀적으로 방문
    for i in graph[v]:
        if not visited[i]: # 미방문
            dfs(graph, i, visited)

# 정의된 DFS 함수 호출
dfs(graph, 1, visited)

"""## - BFS(너비 우선 탐색): 가까운 노드부터 탐색
   - 큐 자료구조 사용
   - deque 라이브러리 사용하는 게 좋음
   - 실제 수행시간 DFS보다 좋은 편

   ### 동작과정
   1. 탐색 시작 노드 큐에 삽입하고 방문처리

   2. 큐에서 노드를 꺼내고, 인접 노드 중 방문하지 않은 노드를 __모두 한번에__ 큐에 삽입하고 방문 처리

   3. 2번의 과정을 수행할 수 없을 때까지 반복
"""

from collections import deque


# 각 노드가 연결된 정보를 리스트 자료형으로 표현(2차원 리스트)
graph = [
  [],
  [2, 3, 8],
  [1, 7],
  [1, 4, 5],
  [3, 5],
  [3, 4],
  [7],
  [2, 6, 8],
  [1, 7]
]

# 각 노드가 방문된 정보를 리스트 자료형으로 표현(1차원 리스트)
visited = [False] * 9

# BFS 함수 정의
def bfs(graph, start, visited):
    # 큐(Queue) 구현을 위해 deque 라이브러리 사용
    queue = deque([start])
    # 현재 노드를 방문 처리
    visited[start] = True
    # 큐가 빌 때까지 반복
    while queue:
        # 큐에서 하나의 원소를 뽑아 출력
        v = queue.popleft()
        print(v, end=' ')
        # 해당 원소와 연결된, 아직 방문하지 않은 원소들을 큐에 삽입
        for i in graph[v]:
            if not visited[i]:
                queue.append(i)
                visited[i] = True

# 정의된 BFS 함수 호출
bfs(graph, 1, visited)
# 1-> 238(거리1) -> 745(거리2)-> 6(거리3) , 큐에는 745 남음

"""# 문제1) 음료수 얼려먹기(DFS)
- 연결 요소(인접한 노드 덩어리)의 수
"""

# N, M을 공백을 기준으로 구분하여 입력 받기
n, m = map(int, input().split())

# 2차원 리스트의 맵 정보 입력 받기
graph = []
for i in range(n):
    graph.append(list(map(int, input())))

# DFS로 특정한 노드를 방문한 뒤에 연결된 모든 노드들도 방문
def dfs(x, y):
    # 주어진 범위를 벗어나는 경우에는 즉시 종료
    if x <= -1 or x >= n or y <= -1 or y >= m:
        return False
    # 현재 노드를 아직 방문하지 않았다면
    if graph[x][y] == 0:
        # 해당 노드 방문 처리
        graph[x][y] = 1 
        # 상, 하, 좌, 우의 위치들도 모두 재귀적으로 호출, 연결된 모든 노드 방문처리
        dfs(x - 1, y)
        dfs(x, y - 1)
        dfs(x + 1, y)
        dfs(x, y + 1)
        return True
    return False

# 모든 노드(위치)에 대하여 음료수 채우기
result = 0
for i in range(n):
    for j in range(m):
        # 현재 위치에서 DFS 수행
        if dfs(i, j) == True:
            result += 1

print(result) # 정답 출력

"""# 문제2) 미로탈출 (BFS)"""

from collections import deque

# N, M을 공백을 기준으로 구분하여 입력 받기
n, m = map(int, input().split())
# 2차원 리스트의 맵 정보 입력 받기
graph = []
for i in range(n):
    graph.append(list(map(int, input())))

# 이동할 네 가지 방향 정의 (상, 하, 좌, 우)
dx = [-1, 1, 0, 0]
dy = [0, 0, -1, 1]

# BFS 소스코드 구현
def bfs(x, y):
    # 큐(Queue) 구현을 위해 deque 라이브러리 사용
    queue = deque()
    queue.append((x, y))
    # 큐가 빌 때까지 반복하기
    while queue:
        x, y = queue.popleft()
        # 현재 위치에서 4가지 방향으로의 위치 확인
        for i in range(4):
            nx = x + dx[i]
            ny = y + dy[i]
            # 미로 찾기 공간을 벗어난 경우 무시
            if nx < 0 or nx >= n or ny < 0 or ny >= m:
                continue
            # 벽인 경우 무시
            if graph[nx][ny] == 0:
                continue
            # 해당 노드를 처음 방문하는 경우에만 최단 거리 기록
            if graph[nx][ny] == 1:
                graph[nx][ny] = graph[x][y] + 1
                queue.append((nx, ny))
    # 가장 오른쪽 아래까지의 최단 거리 반환
    return graph[n - 1][m - 1]

# BFS를 수행한 결과 출력
print(bfs(0, 0))

